server.port: 8081

resilience4j.circuitbreaker:
  instances:
    user:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 10
      failureRateThreshold: 50
      waitInterval: 10000
      ringBufferSizeInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException

resilience4j.retry:
  intances:
    user:
      maxRetryAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - org.springframework.web.client.HttpClientErrorException

spring.cloud.stream.bindings.receiverDeleteNotesChannel:
  destination: deleteNotesChannel
  group: notes

spring.application.name: notes
app:
  users-service:
    host: users

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000

ribbon.NFLoadBalancerPingInterval: 5
